matrix:
  include:
  - os: linux
    dist: xenial
#  - windows

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true


addons:
  apt:
    packages:
      - libgraphite2-dev
      - libharfbuzz-dev
      - libfontconfig1-dev
      - libicu-dev
      - libssl-dev
      - openssl
      - zlib1g-dev
  homebrew:
    packages:
      - harfbuzz
      - openssl

notifications:
  email:false
cache: cargo
